# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build windows 64
      run: GOOS=windows GOARCH=amd64 go build -o build/ccid-amd64.exe main.go
    - name: Build windows 32
      run: GOOS=windows GOARCH=386 go build -o build/ccid-386-32.exe main.go
    - name: Build macos 64
      run: GOOS=darwin GOARCH=amd64 go build -o build/ccid-amd64-darwin main.go
    - name: Build macos arm 64
      run: GOOS=darwin GOARCH=arm64 go build -o build/ccid-arm64-darwin main.go
    - name: Build linux 64
      run: GOOS=linux GOARCH=amd64 go build -o build/ccid-amd64-linux main.go
    - name: Build linux 32
      run: GOOS=linux GOARCH=386 go build -o build/ccid-386-38-linux main.go

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: build/
